name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mah0x211/lua-ci:latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    needs: luacheck
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mah0x211/lua-ci:latest
    strategy:
      matrix:
        lua-version:
          - "5.1.:latest"
          - "5.2.:latest"
          - "5.3.:latest"
          - "5.4.:latest"
          - "lj-v2.1:latest"
    steps:
    -
      name: Switch Lua Version
      run: |
        lenv -g use ${{ matrix.lua-version }}
        lua -v || true
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Install
      run: |
        URL_COVERAGE=1 luarocks make rockspecs/url-scm-1.rockspec
    -
      name: Install Tools
      run: |
        luarocks install testcase
    -
      name: Run Test
      run: |
        testcase ./test
    -
      name: Generate coverage reports
      run: |
        sh ./covgen.sh
    -
      name: Upload c coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        use_oidc: true
        disable_search: true
        files: ./coverage/lcov.info
        flags: unittests

