name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup Lua
      uses: leafo/gh-actions-lua@v8.0.0
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.0.5"
          - "luajit-openresty"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.lua-version }}
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
      with:
        luaRocksVersion: 3.8.0
    -
      name: Install
      run: |
        luarocks make URL_COVERAGE=1
    -
      name: Install Tools
      run: |
        sudo apt install lcov -y
        luarocks install testcase
    -
      name: Run Test
      run: |
        testcase ./test
    -
      name: Generate coverage reports
      run: |
        sh ./covgen.sh
    -
      name: Upload c coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage/lcov.info
        flags: unittests

